### ISSUE TITLE
Drawing latency increases when line profile is active

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1010]
The latency of a live scan increases by up to 1.5x (simulator) and 2x (real cameras) when a line profile is attached to the data item. At the minimum, understand this latency (describe here) or minimize it by changing the code.

Part of the latency is that the measurement is wrong - latency was being measured whenever the Qt process would paint to screen; however this is not correct. Latency should only be measured when paint is preceded by drawing, avoiding paints triggered outside the panel being measured. This [change in nionui-tool](https://github.com/nion-software/nionui-tool/commit/24843d2b04a5769575c53487d24d884385f2ffb1) addresses that issue.

In addition, if a live data item has an attached computation, the thumbnail will be updated regularly. This also throws of the latency calculation in the current code because while the paint will be preceded by drawing, it's not the actual acquired data that is being redrawn, but the latency is measured with the timestamp in the acquired data. This leads to artificially longer latency. The workaround while testing may be to disable thumbnails.

Note: addressed thumbnail problem [here](https://github.com/nion-software/nionui-tool/commit/9d88034ed8247f34c7daf8eb40cb741ad9a3fe86) and [here](https://github.com/nion-software/nionui/commit/fadf492bd523f6e2b1d22785fc319ce8ab424eac).

**Comment by jamesrussell216** [comment]
@Ion-e can you have a look to see if we can recreate this one using the simulated cameras plz?

**Comment by cmeyer** [comment]
It's still a thing and it's a complicated issue that I work on frequently.

Just to mention, it's difficult to see this on the simulator without either fixing or at least temporarily addressing this issue first.

- https://github.com/nion-software/nionswift-usim/issues/44

**Comment by cmeyer** [comment]
Not seeing this anymore. If seen again, file a new issue.

**Comment by Ion-e** [comment]
Verified as fixed, thanks!
