### ISSUE TITLE
Add user interface for locking position/shape of graphics

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#105]
Also consider making the look of the graphic different when locked - SQ.

**Comment by cmeyer** [comment]
MH:

> 1)  I want to be able to lock a graphic such that it can't be resized or moved.  I'd look for a spot in the inspector when the graphic was highlighted to have a little checkbox to lock it.  In illustrator this is accomplished by having a full list of the graphics somewhere, and a little lock symbol that can be done and undone to lock/unlock graphics.

**Comment by TomaSusi** [comment]
That sounds like a great feature.
