### ISSUE TITLE
Zoom resets when moving image around

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#1064]
Pick an image that has more pixels than the display panel displaying it. Switch it to 1:1 view. Move it around with either the arrow keys or the hand tool. This will reset the zoom to scaling the image to the display panel size.
If starting from 2:1 view, it makes the image even smaller than that.

**Comment by cmeyer** [comment]
@Brow71189 I think this is a duplicate of #793. Can you close if so?
