### ISSUE TITLE
Switching libraries when full screen on macOS creates new space and leaves old one blank

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#107]
Toma: When you launch Swift for the first time and make if full screen, it correctly populates its own Space. However, if you switch library, it creates a new Space, leaving the old one as a completely black and non-functional full-screen view (see attached for a screenshot of the OS X Space switcher GUI with three of these).

**Comment by cmeyer** [comment]
Could not reproduce. macOS 11.3. nionswift-tool 0.15.6 (Qt 5.15.2). Closing,

**Comment by TomaSusi** [comment]
> Could not reproduce. macOS 11.3. nionswift-tool 0.15.6 (Qt 5.15.2). Closing,

Confirmed on my system.
