### ISSUE TITLE
Thumbnails do not update when graphics added/removed

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1071]
On any 2D image, add a rectangle by using the Graphics menu. Thumbnail doesn't update. Now adjust rectangle - thumbnail updates. Now delete rectangle. Thumbnail doesn't update. Also occurs on line plots with intervals.

See also:
- https://github.com/nion-software/nionswift/issues/251

**Comment by Ion-e** [comment]
Verified as fixed, thanks!
