### ISSUE TITLE
Remove, disable, or fix unmaintained display script feature

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1080]
The display script was an experimental feature that allowed a user to use a script to generate a display, particularly for matplotlib. The future feature can be discussed here:
- https://github.com/nion-software/nionswift/issues/140

**Comment by Ion-e** [comment]
@cmeyer is there any other instances or locations where this stool can be activated?

**Comment by Ion-e** [comment]
Awaiting for response.

**Comment by cmeyer** [comment]
FYI - there are any other user accessible places - but I think it's possible via scripting.

**Comment by Ion-e** [comment]
Issue verified as fixed, settings as Dondone
