### ISSUE TITLE
Improve workflow for multiple data items for operations like rgb, add, or cross correlation

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#110]
From Niklas December 21 2017:

1) standard operations that take two images, eg cross correlation. Not being able to select the two windows that you want to operate on is very awkward. I proposed before, use the two top most windows in the stack. Control click to select might also work. Trying to find them in the browse window does not work.

**Comment by Brow71189** [comment]
this gets even harder if one of the data items is live data and the other one isn't (you could imagine custom dark subtraction). Would be nice to have but is almost impossible due to how selecting multiple items works.

**Comment by cmeyer** [comment]
With the recent improved selection/action changes, it may now be easier to allow the user to select multiple display panels with each new display panel selected displaying an index number to indicate it is selected.

**Comment by cmeyer** [comment]
Now able to multi-select display panels. Closing.
aa18e1af950201ef483a925c61db8d5493262cd2
