### ISSUE TITLE
For SVG export dialog, show input pixel and calibrated sizes

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1128]
If the user is making choices about the export size and resolution, it is helpful to display the input data pixel size as a reference. Maybe something like "Image Display Size 512x512 (4µm x 4µm)" or "Line Plot Size 1024 (200eV)".

**Comment by jamesrussell216** [comment]
Talked to @lisham2000 about this - proposal is to present that information inside the Export SVG panel at the top just before the user edit boxes.
