### ISSUE TITLE
Add zoom tool

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1137]
See preliminary work and comments in:
- #1073

**Comment by jamesrussell216** [comment]
Gah forgot we added this one as well as keeping this one: https://github.com/nion-software/nionswift/issues/21

Implementation details have gone into the other ticket. I'll try to keep the two tickets together on the Kanban board at least.

**Comment by Ion-e** [comment]
After merge, this should be tested: 
https://github.com/nion-software/nionswift/issues/1181

**Comment by cmeyer** [comment]
Closed c2a389a334136871d3bfd513a7e40a0f8dbd646c

**Comment by Ion-e** [comment]
Implemented.
