### ISSUE TITLE
Bug - Inspector: graphic inspector center button has broken functionality

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1158]
The button to centre graphiis in the display items is broken when attempted to be used from the *display item* inspector.
The button works correctly from the graphic's own inspector.

Please take in consideration that because the item selected is the "display item", what would we expect about pressing the centre button here? To affect all graphics?

**Comment by jamesrussell216** [comment]
There's one centre button for each graphic object (when you have the underlying data object selected), so I would think that clicking on a graphic object's respective centre button would centre just that respective object.

**Comment by Ion-e** [comment]
Issue verified as fixed, thanks!
