### ISSUE TITLE
Control + Z doesn't remove the Lattice tool

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1159]
As title.

**Comment by jamesrussell216** [comment]
@Ion-e I just tried this (put down a lattice tool, CTRL-Z) and it worked fine, so has this been fixed or am I missing something?

**Comment by cmeyer** [comment]
This will only fail if you add it to a data item with a computation such as FFT attached.

**Comment by Ion-e** [comment]
Issue verified as fixed, thanks!
