### ISSUE TITLE
Add controls for brightness, contrast, and gamma

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#116]
`I' = I ^ gamma`

**Comment by cmeyer** [comment]
See http://www.ericbrasseur.org/gamma.html

**Comment by ndellby** [comment]
Our data is different, if the image data is as in his example, the correct scaling should give a gray rectangle, you could argue that the correct gamma curve would make the unscaled image look gray as well.

**Comment by cmeyer** [comment]
cd7067d1325c4c7c63d671d8b04ec780ec1c05b5
