### ISSUE TITLE
Bug - Software fails to show data or display items when launching from nionswift/pull/1073

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1181]
When launching software from nionswift/pull/1073, all other repos on Master

STR: 
1. Create a project.
2. Generate a data item with 44x24 size.
3. Start the usim cameras.
4. Observe the issue.

Data and Display items seem broken.
![image](https://github.com/user-attachments/assets/d78542fe-7a3a-46cb-b745-69c1ba84d582)
From testing https://github.com/nion-software/nionswift/issues/1137, blocked until this issue has been merged.

**Comment by cmeyer** [comment]
Yes, that's correct. All PR's, including #1073, need to be rebased on or merged with the main branch.

**Comment by Ion-e** [comment]
Issue fixed with rebasing.

Thanks everyone.
