### ISSUE TITLE
Swift Force closing

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1197]
Happened a few times. Managed to get a reproduceable steps, although it's possible that different issues are also causing crashes/force closes/freezes.

STR: New project > Rename the project to an existing Project in the chosen folder > Create > Repeat (60%ish of triggering)

Same behaviour has been observed by using the "Recent Projects" or "Open Project".

In a particular case, the 2 latest snapshots were lost.

**Comment by cmeyer** [comment]
Can you revisit this after updating nionui-tool? The commit that probably fixes this is nion-software/nionui-tool@a1767987ab0161dac9b1abdffbbf58f558ce162a

**Comment by jamesrussell216** [comment]
@cmeyer I had a look today - it's still doing it for me on the new build I'm afraid. Took me a few goes though (~4).

**Comment by cmeyer** [comment]
Can you recheck this after you updated nionui-tool last night? Thanks.

**Comment by cmeyer** [comment]
Can you give me the exact steps you're using to trigger the problem? In the past I've tested by repeatedly using the menu item File > Recent Project and going back and forth between two projects. I cannot get a crash with that sequence of steps. What is your list of steps?

Ideally expressed like this:

1. Launch Swift
2. Choose menu item File > Recent Project and choose the first project at the top
3. After it opens, repeat step 2 until crash.

**Comment by jamesrussell216** [comment]
Yep...

1. Launch Swift
2. File > New Project
3. Enter a Project Name that is the same as an existing project (in the Projects Folder).
4. Create Project
5. Wait ~5 seconds while Swift either reloads the new project fine, or reloads the new project then crashes out.
6. If no crash, repeat from step 2 until crash.

**Comment by Ion-e** [comment]
No crash recorded anymore.

Issue verified as fixed.
Thanks!
