### ISSUE TITLE
Inspector: Fill colour doesn't seem to work correctly

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1205]
When adding composite line plots, the second line plot fill colour appears as Blank.

Happens on Master.

**Comment by Ion-e** [comment]
Added to PR

**Comment by jamesrussell216** [comment]
@Ion-e is this a bug or intended?

**Comment by Ion-e** [comment]
That wouldn't be a question for me but for @cmeyer.  I cannot see a use case for it being working as intended.
Behaviour still persists.
I'm happy if this is not in the Kanban board, however I wouldn't removed the "Bug" type until we have more info on the behaviour.

**Comment by cmeyer** [comment]
The intended behavior is that only the first layer is filled. Subsequent layers are stroked, but not filled. The idea is to reduce clutter with the subsequent layers.

Are you reporting something other than this behavior?

**Comment by Ion-e** [comment]
> The intended behavior is that only the first layer is filled. Subsequent layers are stroked, but not filled. The idea is to reduce clutter with the subsequent layers.
> 
> Are you reporting something other than this behavior?

This ticket is about that behaviour only. Other issues will be reported in different tickets. 

Closing issue as per comment, thanks!
