### ISSUE TITLE
List of graphics in inspector doesn't update on a undo/redo command

### ISSUE THREAD

**Issue by KRLango** [nion-software/nionswift#1219]
To recreate:

- Create a display item.
- Add 3 graphics to the display item.
- Select the display item and check the graphics inspector section: there should be 3 graphics there.
- Delete 1 of the graphics.
- Select the display item and check the graphics inspector section: there should be 2 graphics there.
- Press Ctrl+Z (or equivalent)
- Check the graphics inspector section: there should be 3 graphics there now, but there are only 2.

**Comment by Ion-e** [comment]
Issue verified as fixed, thanks!
