### ISSUE TITLE
Line Profiles - Subsequent layers don't always inmediatly update.

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1224]
When adding a second layer to the usim EELS camera *Display item*, the second layer doesn't visually appear until you press play.
*This has also been observed on persistent Data items.*

Potentially related to:
https://github.com/nion-software/nionswift/issues/1212

**Comment by cmeyer** [comment]
Need steps to reproduce.

**Comment by Ion-e** [comment]
Sent to testing for STRs.

**Comment by Ion-e** [comment]
This seems fixed already (or not reproduceable anymore), if this hasn't been fixed ping me @cmeyer and I will reopen and test more thoroughly.
