### ISSUE TITLE
The Acquire button for scans seems to be disabled until you run Scan on the Scan controls

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1230]
Uncertain on whether this happens only on simulator.
![Image](https://github.com/user-attachments/assets/eed2b7c3-3c9b-44c8-a818-62c1c11aa4af)

1. Launch a new project.
2. Open the Acquire Window.
3. Select Configuration shown in the aforementioned image.
4. Observe the "Acquire" button will be disabled.
5. Open the Scan tool
6. Click on Scan.
7. Observe the "Acquire" button will become enabled.

**Comment by Ion-e** [comment]
Discarded as per designed.

**Comment by cmeyer** [comment]
Wrong repo, too: https://github.com/nion-software/nionswift-instrumentation-kit/issues
