### ISSUE TITLE
Can't delete 2 graphics using Control Z

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1241]
As title, (sorry, unsure if duplicate ticket for this issue).

Add 2 different graphics, attempt to remove them by using control Z.
Only the last one added will be removed.

**Comment by jamesrussell216** [comment]
@Ion-e can you check if this is still a thing post @cmeyer check in ref above?

**Comment by Ion-e** [comment]
Issue verified as fixed, works great now, thanks!
