### ISSUE TITLE
Can't access all the API interface through 'run script'

### ISSUE THREAD

**Issue by kociak** [nion-software/nionswift#168]
When trying to access `api.library.get_data_item_for_reference_key(reference_key)` from a run script, an error message is generated:
> AttributeError: 'Library' object has no attribute 'get_data_item_for_reference_key'

And indeed, when introspecting the `api.library` object from within the run script environnement, one discovers that it is a `<class 'nion.swift.FacadeQueued.Library'>` that indeed as no attribute get_data_item_for_reference_key.
Please let me know how we can access this method.
Thanks

**Comment by cmeyer** [comment]
Closing this. It works in the current version. See also #218.
