### ISSUE TITLE
Provide option for help text associated with a Run Script

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#176]
ND:

in AS2 we have help for alignment windows, it works as follows:

The file for the window has a name  xyz.xml

If there also exists a file xyz.rtf then when you run it you get a help button on the bottom, and if you click the help button it opens the rtf file in wordpad.

We need the same for the scripts.

**Comment by Brow71189** [comment]
Same would be nice for plug-ins. Could be a docstring or README or a different file that is shown when you click help.

**Comment by cmeyer** [comment]
Closing this as complete. Open new issues for additional functionality or request changes to the functionality.
