### ISSUE TITLE
Line profiles on complex data should show modulus, not log-modulus

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#223]

**Comment by Brow71189** [comment]
With #413, you can now at least change the display type of the image to "absolute", which will also make the line profile show the "absolute" data and not the "log-absolute" anymore.
I'm not sure if this is good enough to consider this issue fixed though.

**Comment by cmeyer** [comment]
Another option to discuss before closing: maybe the goal should be to have line plot display real and complex in separate display layers?
