### ISSUE TITLE
Computations on FFT should use data instead of display_data

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#241]
Requested by ND

If you apply further computations on the result of an FFT, you usually do not want to work on the logarithm of the power spectrum (which is what happens at the moment), but on the complex data. Right now "inverse FFT" is the only computation that (somewhat) works properly for FFT data.

**Comment by cmeyer** [comment]
The only computation using display_xdata is the line profile. Closing this issue since that issue is tracked in #223.
