### ISSUE TITLE
Review cropped_display_xdata scaling

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#276]
In email from BP/ND on 2019-04-08, they divide a line plot by itself and end up with non 1.0 value.

**Comment by cmeyer** [comment]
￼

**Comment by cmeyer** [comment]
![image](https://user-images.githubusercontent.com/34664/80283956-3a709e00-86d0-11ea-9fda-5b4754cfe3b3.png)

ND: Doing division of two four pixel wide line profiles, it gets normalization wrong, note that equation is dividing one by itself.

**Comment by Brow71189** [comment]
I can't reproduce this anymore, maybe it is already fixed? Of course I don't have the data that they used, but when I divide some data by itsel I get a straight 1.0:

![grafik](https://user-images.githubusercontent.com/16721195/80376327-f29d7280-8899-11ea-8b8d-38806ac4d5ef.png)

**Comment by cmeyer** [comment]
Closing: unreproducible.
