### ISSUE TITLE
API seems to behave inconsistent between scripts and python console 

### ISSUE THREAD

**Issue by MEisebitt** [nion-software/nionswift#305]
If I let the following code execute in the python console:
`api.library.data_items[0].intensity_calibration`
it returns:
`x 1.0 + None`

But if I run the following script:
`def script_main(api_broker):`
`        interactive = api_broker.get_interactive(version='~1.0')`
`        api = api_broker.get_api(version='~1.0')`
`        print(api.library.data_items[0].intensity_calibration)`
it returns:
`x 1.0 + None offset:0 scale:1 units:''`

**Comment by cmeyer** [comment]
The print statement uses `__str__` to get the printable string. The console (with no print statement) uses `__repr__`.

Try this in the console:

```
>>> api.library.data_items[0].intensity_calibration
x 1.0 + None counts
>>> print(api.library.data_items[0].intensity_calibration)
x 1.0 + None counts offset:0 scale:1 units:'counts'
>>> api.library.data_items[0].intensity_calibration.__repr__()
'x 1.0 + None counts'
>>> api.library.data_items[0].intensity_calibration.__str__()
"x 1.0 + None counts offset:0 scale:1 units:'counts'"
```
