### ISSUE TITLE
Cookiecutter template/skeleton for plugins

### ISSUE THREAD

**Issue by ericpre** [nion-software/nionswift#307]
It would be useful to have a cookiecutter tool to make new plugins. The [cookiecutter for pytest plugin](https://github.com/pytest-dev/cookiecutter-pytest-plugin) is a good example.

**Comment by cmeyer** [comment]
Good idea. I looked into this briefly in August but got caught up in other issues.

**Comment by cmeyer** [comment]
This is a work in progress, but here is an initial version:

https://github.com/nion-software/cookiecutter-nionswift-plug-in

Once you have installed cookiecutter ([documentation](https://cookiecutter.readthedocs.io/en/stable/README.html)), you can create a new Nion Swift plug-in using the following command:

`cookiecutter gh:nion-software/cookiecutter-nionswift-plug-in`
