### ISSUE TITLE
Display items should show title based on template string.

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#32]
The displayed title might be something like "{title}" for backwards compatibility. But the goal would be to allow titles to display other metadata such as date/time; session; processing; etc.

```[tasklist]
- [ ] Define list of slugs, i.e. `device`, `device-channel`, `device-brief`
- [ ] Decide on back-tick or braces?
- [ ] Decide on underscore or hyphen for word separator?
- [ ] Decide on domains: display items, graphics, anything else?
- [ ] Support `sample-name`, etc. <- should look through sources and find the first one with a `sample-name`
- [ ] Support registering slugs from packages
- [ ] Most operations should register a default slug to be changed in preferences, i.e. `{default-computation}`
- [ ] Allow nested slugs like `{default-capture}` = `{device-brief} {unique_number}`
- [ ] Save the template plus latest slug values, recursively; this facilitates missing packages and new features
- [ ] Allow code to do rendering for a particular slug, i.e. not strictly a string replacement
- [ ] Implement cascade system for slug values, i.e. display item title overrides data item title.
- [ ] Disallow recursive slugs, with check in code
- [ ] Decide how to treat invalid slugs due to wrong name or missing metadata
- [ ] Decide how to handle propagation - is there some sort of root name?
- [ ] Dynamic graphics should handle calibrated coordinates
- [ ] Slugs should be able to display the result of a computation in a graphic region (mean value, max value, etc.)
```

See also:

- #826
- #383

**Comment by cmeyer** [comment]
Allow numbering, sample info, etc.

Extended request by QR.

**Comment by cmeyer** [comment]
From ND:

We could add an "automatic naming feature"
Any snapshot would be automatically named as:
Sample+location+sequence number+data type

Where location is named in the stage control, we already have this. Sample is the sample name. And sequence number just counts at that location.

So you would get names like:
SiN3-thin area-43-HAADF rather than "snapshot of haadf"

**Comment by ndellby** [comment]
Remember Quentin's comment, decorations should be appended not prepended, Thus SiN-HADF should become "SiN-HADF-43-snap-FFT"
 rather than "FFT of snapshot of HADF SiN 43"
This sorts better and when text is truncated you don't get "FFT of Snapshot of..."

**Comment by TomaSusi** [comment]
YES.

**Comment by cmeyer** [comment]
Personal notes from 2021-09-03:

- Only used substitutions for dynamic content; not structure?
- {src-title}{processing}{r-var}
- "Ronchigram (FFT)"
- "src-title" is the source title or this items title if specified
- "processing" is the processing description slug
- "r-var" is the assigned ref var - treated separately.
- Q: How do I deal with the fact that processing occurs on a data item, but the title is associated with the display item?
- Q: For `src-title`, what title is used? The rendered title or just the `src-title` of the source?
- "Ronchigram (FFT) (Inverse FFT)"
- Overarching goal is to make it easier for the user to label the data.
- {device}{signal-type}
- "EELS Camera Spectrum"
- {signal}
- "EELS Spectrum"
- {collection-style}
- {dimensions}
- {acquisition-id}

**Comment by cmeyer** [comment]
See also:

- #383
