### ISSUE TITLE
Investigate intermittent UI hangs while using large data items

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#346]
May be related to HDF5.

**Comment by cmeyer** [comment]
Fixed https://github.com/nion-software/nionui/commit/209dcfb92b5de68bc81a490f2f1a5a079bc1b4e6

**Comment by Brow71189** [comment]
The partial updates during 4D data acquisition cause the UI to freeze frequently or even for the whole duration of the acqusition. Possibly this is due to writing the data out to disk continously.

**Comment by cmeyer** [comment]
Closing this. I think we've worked out the issues. Make a new issue with specific details if necessary.
