### ISSUE TITLE
Starting from developer installation fails due to niondata version mismatch

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#348]
nionswift depends on niondata >= 0.13.10 but the current master branch of niondata is 0.13.9

**Comment by cmeyer** [comment]
Try launching nionswift-tool directly:

On macOS:
`/path/to/miniconda3/envs/nionswift-dev/bin/nionswift-tool nionui_app.nionswift`

It will be similar on Windows or Linux.

**Comment by cmeyer** [comment]
This can be closed now, right?

**Comment by Brow71189** [comment]
Yes

Chris Meyer <notifications@github.com> schrieb am Mo., 25. Mai 2020, 03:03:
