### ISSUE TITLE
Line plot displays negative data strangely when display on log-y scale

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#392]
`show(numpy.arange(-2,5,0.01))` then switch to 'Log Y' then drag axis upwards.

![image](https://user-images.githubusercontent.com/34664/80621232-dd405980-89fb-11ea-9a5d-a570b0997f2c.png)

This is going to require a change to our graphing algorithm and we need to be careful not to impact performance. My first thought is that there will need to be some ability to just not plot the negative data - so as we draw from left to right, we will need to track whether we are drawing or not for any given column and generate appropriate draw commands when switch from drawing to not drawing state. This is the part that may affect performance.

**Comment by cmeyer** [comment]
@Brow71189  Is this still an open bug?

**Comment by Brow71189** [comment]
Just tested it and it is not an issue anymore:

![grafik](https://user-images.githubusercontent.com/16721195/89305910-80de7d00-d66f-11ea-8cfc-34ad704855ef.png)
