### ISSUE TITLE
Go to source/dependent in context menu should not show full title

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#403]
That is one huge context menu:

![grafik](https://user-images.githubusercontent.com/16721195/81314641-a9170980-9089-11ea-871a-8f897ea5cf30.png)

**Comment by cmeyer** [comment]
This also fits in with making titles more flexible/dynamic. See #32 (dynamic titles).

**Comment by Brow71189** [comment]
Yes, but in general the titles in the context menu should not exceed a certain length. I would just could them after a certain number of characters so that the context menu stays under a reasonable width.

**Comment by cmeyer** [comment]
I'd like to add support for text truncation (elision), which is truncation based on character width. And it would be nice to truncate from the middle and replace with an ellipsis. There is no perfect solution for truncation (beginning, middle, end), but I tend to think our names have important information at the beginning and end.

I've added support for truncation to `nionui` but this will not be active until the tools update to 0.4.5. It is available in the PySide2/pyQt version immediately.

**Comment by cmeyer** [comment]
3fc6def83ca880731a5714bc00803772c5fb78f2
