### ISSUE TITLE
Consider creating sub-menus in the context menu.

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#405]
The context menu tends to get pretty lenghty and a bit confusing at times, especially with many acquistion devices installed in a system:

![grafik](https://user-images.githubusercontent.com/16721195/81316708-34919a00-908c-11ea-83d0-55d2370ea65c.png)

Maybe we could group the devices into sub-menus like Scan, Cameras, Video Cameras or something similar?

**Comment by cmeyer** [comment]
Done.
