### ISSUE TITLE
Certain combinations of number of pixels and display width make log-line plots disappear

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#463]
I couldn't figure out what exactly triggers this, but one way to reproduce the issue is to acquire a spectrum with the usim eels camera, switch the display to log scale and zoom out on the x-axis. At some point the spectrum diappears.
Alternatively you can also make the image panel narrower (for example by doing "Split Into Left and Right"), which will also make the plot disappear.

Without log scale I never saw the problem.

Interestingly, similar data like `show(numpy.random.rand(1024))` does not show the problem.

**Comment by cmeyer** [comment]
This might be happening without log display too. Doing live 1D acquisition, the thumbnail flickers with data and no-data.

**Comment by cmeyer** [comment]
The line plot calculates left and right data channels, but checks whether they are within range of the data. If not, the drawing is skipped.

https://github.com/nion-software/nionswift/blob/8bd826436ecb26fe00e4644e09e23752a8f9f30a/nion/swift/LineGraphCanvasItem.py#L354-L365

Also see 8bd826436ecb26fe00e4644e09e23752a8f9f30a.

**Comment by cmeyer** [comment]
Closing this until a specific example is found.
