### ISSUE TITLE
TypeError in model/FileStorageSystem.py

### ISSUE THREAD

**Issue by yvesauad** [nion-software/nionswift#473]
```
    def __read_properties(self):
        properties = dict()
        if self.__filepath and os.path.exists(self.__filepath):
            try:
                with open(self.__filepath, "r") as fp:
                    properties = json.load(fp)
            except Exception:
                os.replace(self.__filepath, self.__filepath + ".bak")
        # migrations go here
        return properties
```

If you go inside the exception, `os.replace(self.__filepath, self.__filepath + ".bak")` gives you a TypeError in python 3.8.3.

- Unsupported operand type(s) for +: 'WindowsPath' and 'str'

I had a crash (unrelated to swift) and he was not finding my properties I guess.

`os.replace(self.__filepath, str(self.__filepath) + ".bak")` did the trick to me.

**Comment by cmeyer** [comment]
Thanks for this report. This was fixed a while ago bbfb3cea636a2dd093963b3308ce4ae60adff581. Closing.
