### ISSUE TITLE
Scripts dialog sorts scripts wrong. 

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#474]
Because we use simple comparison between strings with the builtin ``<`` and ``>`` operators, small letters will be sorted after all capital letters, so for example a script called ``a_script.py`` would appear after ``Zero_script.py``.

Here  is the place in the code where sorting happens:
https://github.com/nion-software/nionswift/blob/4a3b642b7ca9debec3107a130e2c8b7ff55693b6/nion/swift/ScriptsDialog.py#L236

A simple fix would be to compare the strings after converting them to lowercase, but that would still not fix issues with scripts having numbers in their file names.
A proper fix would use ``natsort`` for sorting (https://github.com/SethMMorton/natsort). This is a python-only library which does not have any extra dependencies. It is also available through conda. Would you be willing to add that as a dependency for Swift?
If so, I'll make a fix involving ``natsort``, if not I'll just go for the simple fix.

**Comment by cmeyer** [comment]
4e13730f2da368f3bef94148e2e6ab8c7af2ece5
