### ISSUE TITLE
Version 2 projects should be upgraded (silently or with confirmation) to version 3

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#488]
Version 3 does not include connections - so writing to a version 2 project will make it incompatible with older versions of Swift.

**Comment by ndellby** [comment]
Remember, all old obsolete version projects must be readable by all 
future versions, and tests must be added.

Phil has more than once pulled up APL projects with data and 
calculations from 30 years ago and just run them.

If upgrading old stuff breaks old analysis that's a problem.

**Comment by cmeyer** [comment]
@ndellby This version loads all previous versions. There are a total of 16 file versions -- 13 "library" versions and then renamed to "project" and now 3 project versions). There are tests for all versions.
