### ISSUE TITLE
Enable auto-chunking on HDF5 files

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#519]

**Comment by Brow71189** [comment]
Do you mean auto-chunking like the actual h5py `chunks=True` option or some chunking based on our data layout (i.e. SI or 4D data)?

**Comment by cmeyer** [comment]
Good point. Let's start with chunks=True ... but maybe we should switch things around so that instead of passing around `large_format` to various creation methods, we pass `data_descriptor`. Then the low level IO can have more control over how it manages chunking. I'll remove the "easy" tag now.

**Comment by cmeyer** [comment]
As a side note, we might want to continue performance tests before proceeding with this too much further. We need to answer the question: Is datum-shape chunking really better then auto?
