### ISSUE TITLE
Right click menu options to see file in file browser as well as copy full path

### ISSUE THREAD

**Issue by tcpekin** [nion-software/nionswift#534]
Both of these options upon right clicking a data item would help analyze data outside of Swift.

**Comment by cmeyer** [comment]
In the current version (version 15), files within Swift projects are considered to be private and it's my goal to not have users access them directly. My general plan has been to eventually fully isolate data files from other parts of the project. And right now, there is only one item left: `source_specifier` in `DataItem`. However, overall, making data files independently usable is a longer term project.

If you have a specific use case that you would like Swift to support (more specific than "be able to access individual data files"), please file a new issue.

You might also be interested in the issue I filed earlier today: #539: provide API for accessing data items from Python without the Swift UI being launched.
