### ISSUE TITLE
Double Gaussian does not work in 0.15.2 version

### ISSUE THREAD

**Issue by PhysXu** [nion-software/nionswift#585]
No response after clicking the **Double Gaussian** in **Processing** of 0.15.2 version.
![image](https://user-images.githubusercontent.com/35793078/102035147-abe59400-3dfa-11eb-9210-ab6dfd7960d9.png)

**Comment by Brow71189** [comment]
Fixed in https://github.com/nion-software/experimental/commit/ab5a9d03952c2118d0b07e05295f4b4b8f8a33b4
