### ISSUE TITLE
Importing data with UUID matching existing item fails with no error message

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#592]
There is a log message printed.

Note: duplicate UUID's can occur by
- importing a new file that matches an item already in the project
- by importing two files that have the same UUID

In the short term, we should just create a new UUID for each data item imported.

See
- #1044

**Comment by Brow71189** [comment]
What's the intended behavior? Should it just show a more prominent error message? Should it still import the item but assign a new uuid? Should it overwrite the exisiting item? Should it put the existing item into the panel the user imported the duplicate item to?
