### ISSUE TITLE
Info panel does not display anything for sequence of collection of 2D data (5D)

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#617]
Create an image using Generate Data which is a sequence (3) of a collection (4x4) of images (5x5). Mouse over the resulting image and the associated pixel info should show up in the Info panel.

![Image](https://github.com/user-attachments/assets/4a631806-6e02-42f9-b073-af56897e509c)

**Comment by Ion-e** [comment]
Issue verified as fixed, thanks!
