### ISSUE TITLE
There is no file format for exporting/importing composite line plots

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#630]
Make a line plot with multiple layers. Try to export.

1. Use Processing > Generate Data... to create two 1D data items
2. Drag the title of the 1st one to the content area of the 2nd one to create a composite line plot
3. Click on the data panel with the composite line plot (the one showing both 1D data items in a single plot)
4. File > Export... and then click Export
5. No file is produced.

Explanation: Exporting was originally defined for _data_ not displays. The existing plug-in architecture only loosely supports the infrastructure for exporting a "display"; and it is not clear what it means to export multiple 1D (or 2D in the future) data items into anything other than a display-style image.

If the user wants individual pieces of data, are there formats available for that? Answer: probably HDF5 and similar.

Do we allow exporting and then re-importing of that data?

(refer to internal discussion)

<img width="369" alt="image" src="https://github.com/nion-software/nionswift/assets/34664/e21576c1-5e71-4ccb-aac8-416992eb21b5">

<img width="306" alt="image" src="https://github.com/nion-software/nionswift/assets/34664/4589c05a-d1d6-4568-9414-247f465352bd">

**Comment by jamesrussell216** [comment]
Hi @cmeyer @Brow71189 just been discussing this one with @KRLango and realised we don't understand it! Could we have a bit more context please?

**Comment by cmeyer** [comment]
PR
- https://github.com/nion-software/nionswift/pull/1243

**Comment by cmeyer** [comment]
Fixed #1243
