### ISSUE TITLE
Updating the Developer Installation Wiki page

### ISSUE THREAD

**Issue by icbicket** [nion-software/nionswift#631]
I was able to follow the instructions fairly well to install the developer version (with some modifications for my system and desired install), but I noticed a couple of inaccuracies in the [Wiki](https://github.com/nion-software/nionswift/wiki/Developer-Installation).
- the page references nion-instrumentation ("https://github.com/nion-software/nion-instrumentation.git") as a repo to clone, but this repo doesn't exist publicly, I suppose it may have been renamed to nion-instrumentation-kit?
- I found pyqt5 was also necessary to have in the virtual environment.

**Comment by cmeyer** [comment]
I updated the Wiki page by removing references to nion-instrumenation (and internal-to-Nion package) and updating the explanation of how Swift is launched.

You should not need `pyqt5` - the recommended developer setup launches Swift using `nionswift-tool`. But if you can't get that running with the new explanations on the Wiki page, either file a new issue or re-open this one.
