### ISSUE TITLE
Grid browser takes unnecessarily long time to open

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#645]
With a large-ish project, make a new workspace, 2x2, change top left panel to grid browser.

This is probably something to do with thumbnail computations.

Reported by ND 2021-03-23.

**Comment by Brow71189** [comment]
Could this be related to #636 ? I think it is likely to be the same underlying problem.

**Comment by cmeyer** [comment]
Yes, quite possibly. I'll take a look at both of these in the next few days.

**Comment by cmeyer** [comment]
Closing. I cannot reproduce this on several machines.
