### ISSUE TITLE
About Dialog broken (invalid file name)

### ISSUE THREAD

**Issue by niermann** [nion-software/nionswift#667]
Menu point Help/About... does nothing.

Console gives indication to the reason:
FileNotFoundError: [Errno 2] No such file or directory: '[...] lib/python3.7/site-packages/nion/swift/resources/logo3.png'

The actual file is named Logo3.png (uppercase). Renaming the file to logo3.png (lowercase) resolves the problem.

Environment: 
* Ubuntu 18.04 with Python 3.7 from ubuntu-toolchain-r PPA.
* Nionswift 0.15.5 installed from PyPI into Python 3.7 virtual environment with upgraded pip
* Additionally PySide2 installed (from PyPI), nionswift-tools **not** installed

**Comment by cmeyer** [comment]
@niermann thanks for reporting!
