### ISSUE TITLE
Preferences dialog broken

### ISSUE THREAD

**Issue by niermann** [nion-software/nionswift#675]
Calling "Preferences..." from menu does nothing (at least in my setup).

From the console this can be traced back to a failed assertion in :
>File .../nion/ui/PreferencesDialog.py", line 70, in change_selection
>assert 0 <= index < len(preference_pane_delegates)

Environment:
*  Ubuntu 18.04 with Python 3.7.9 from ubuntu-toolchain-r PPA.
*  Nionswift 0.15.6 installed from PyPI into Python 3.7 virtual environment with upgraded pip (according to installation instructions)
*  nionswift-tools 0.4.10 with python path fixed (see issue no. 3 of nionswift-tool) installed

Full console output (/home/niermann/swift is the virtual environment, the warning about the histogram appears always/seems unrelated to this issue)
>Using Python environment: /home/niermann/swift
>Launch time 2021-04-13 14:24:33.920406
>Python version 3.7.9 (default, Oct  9 2020, 12:27:12) [GCC 8.4.0]
>User interface class QtUserInterface / HostLibProxy
>Qt version 5.9.5
>Application data: /home/niermann/.config/Nion/Nion Swift/nionswift_appdata.json
>Loading plug-ins from /home/niermann/.local/share/Nion/Nion Swift/PlugIns
>NOT Loading plug-ins from /home/niermann/Documents/Nion/Swift/PlugIns (missing)
>Plug-in 'nionswift_plugin.DM_IO' loaded (nionswift_plugin).
>Plug-in 'nionswift_plugin.TIFF_IO' loaded (nionswift_plugin).
>Plug-in 'nionswift_plugin.none' loaded (nionswift_plugin).
>NOT Loading color maps from /home/niermann/.config/Nion/Nion Swift/Color Maps (missing)
>Using existing profile /home/niermann/.local/share/Nion/Nion Swift/Profile.nsproj
>Using cache /home/niermann/.local/share/Nion/Nion Swift/Profile Cache.nscache
>Loading project /home/niermann/Documents/Nion Swift Project 20210327.nsproj
>Welcome to Nion Swift.
>/home/niermann/swift/lib/python3.7/site-packages/nion/swift/HistogramPanel.py:572: RuntimeWarning: invalid value >encountered in sqrt
>  rms = numpy.sqrt(numpy.mean(numpy.square(numpy.absolute(data))))
>Traceback (most recent call last):
>File "/home/niermann/swift/bin/NionSwiftLauncher/bootstrap.py", line 25, in bootstrap_dispatch
>return getattr(object, method_name)(*args)
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/QtUserInterface.py", line 1700, in triggered
>self.trigger()
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/UserInterface.py", line 2486, in trigger
>self.on_triggered()
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/Window.py", line 681, in perform_action
>self.perform_action_in_context(action_id, self._get_action_context())
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/Window.py", line 687, in perform_action_in_context
>if action.invoke(action_context).status == ActionStatus.MODAL:
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/Window.py", line 985, in invoke
>open_preferences()
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/swift/DocumentController.py", line 782, in open_preferences
>preferences_dialog = PreferencesDialog.PreferencesDialog(self.ui, self.app)
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/PreferencesDialog.py", line 119, in __init__
>rebuild()
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/PreferencesDialog.py", line 114, in rebuild
>change_selection({selected_index})
>File "/home/niermann/swift/lib/python3.7/site-packages/nion/ui/PreferencesDialog.py", line 70, in change_selection
>assert 0 <= index < len(preference_pane_delegates)
>AssertionError

**Comment by cmeyer** [comment]
This is due to there being no preference panels. I've made a quick patch to cover that case here:

https://github.com/nion-software/nionui/pull/40
