### ISSUE TITLE
Thumbnail caching is stored in profile cache and has no garbage collection

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#679]
Rethink where thumbnails are stored. They should probably be stored with the project, either in a sibling, in `.nsproj` file, or in the primary data directory.

- store thumbnails at same level as `.nsproj`
- add fields for last accessed, last updated, last modified
- consider less fragile thumbnails (zoom/offset should not invalidate)

last accessed can be used to clean out old data; last updated and last modified can be used to determine if the data is valid (replaces the dirty flag).

**Comment by cmeyer** [comment]
From email today:

> The problem is the cache file is shared by any project - so you can delete the cache file and create a new project, but once you open a large project, Swift will try to recreate all of its thumbnails and store them in the cache file. Then returning to the new project will still have the negative effects of the large cache file.
> 
> Can you try this for now? Create a new Swift project or switch to a smaller one. Exit Swift. Delete the cache file. Relaunch Swift. This procedure should guarantee good behavior until you load a large project again. You can follow this same procedure if it reoccurs.
>

**Comment by kociak** [comment]
the "started event/thread" things seems unrelated after few tests
