### ISSUE TITLE
Line plot drawing unstable when dragging y-axis

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#681]
`show(numpy.random.randn(100,) * -20000)` then drag the y-axis. The left edge of the plot / right edge of the y-axis captions jitters back and forth.

**Comment by dhauge** [comment]
Looks like the main problem is in the calculation of the size required for labels on the vertical axis in `LineGraphVerticalAxisScaleCanvasItem.size_to_content`. The size required for a label is based on an upper/lower bounds calculated from the min/max calibrated value, and the number used is the one corresponding to the bound itself, not the nearby rounded value that will actually be displayed, so it tends to have non-zero digits in every position (e.g. `661794`, and the exact numbers vary widely as the axis is dragged. If the font is not monospaced, the calculated width will depend on the exact digits in the bounds, and will thus vary as the digits change.
