### ISSUE TITLE
Remove delete button in the Edit Computation dialog

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#832]

**Comment by cmeyer** [comment]
Sounds good. I'm not sure why I put that in there in the first place.

I'll change the title and add this to my priority list.

Also, for reference:
- https://github.com/nion-software/nionswift/issues/594

**Comment by jamesrussell216** [comment]
:reasons:

No need to put it on your list; we can sort this easy enough.

**Comment by cmeyer** [comment]
Sounds good - for clarification my "add to my priority list" comment meant I'll add prioritization labels so it doesn't get lost in the shuffle, which I did already.

**Comment by Ion-e** [comment]
Verified as fixed, thanks!
