### ISSUE TITLE
Stacked line plots do not correctly view-to-interval

### ISSUE THREAD

**Issue by gosselind1** [nion-software/nionswift#866]
Steps to reproduce:
1. Generate two lineplots
2. Drag one over the other to create a stack
3. Add an interval graphic
4. Press enter to zoom in

Expected Behavior:
Zooms into a window looking similar to this:
![image](https://user-images.githubusercontent.com/36932274/176798750-8315f90a-27cb-4a46-849f-78318c096a56.png)

Actual Behavior:
Zooms into a window which only accounts for the first layer (the light blue one in this case)
![image](https://user-images.githubusercontent.com/36932274/176798842-9fa1b414-f1a8-4e0d-905c-db9378ac6204.png)

**Comment by cmeyer** [comment]
Additional comment (from chat):

I think that in the case of view-to-intervals, that it would make sense to translate the interval to graph coordinates (pixels) and then back to each layer's fractional coordinates and then determine the appropriate y-values (in pixels) for that layer - then use the min/max across all layers to figure out y-scaling. x-axis adjustment is obvious and can be done using any layer.
