### ISSUE TITLE
Minimizing and maximizing window can result in counterintuitive behavior

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#940]
For example, if you had Swift maximized when you last closed it, this will be the saved state. If you now change to windowed mode while it is up, and then minimize and restore Swift it will return to maximized instead of windowed.
The same happens for the panel arrangement within Swift: After minimizing and restoring the Swift main window you get the arrangement from when you last exited Swift, not from when you minmimized it.

**Comment by jamesrussell216** [comment]
That just sounds like a bug to me.

**Comment by cmeyer** [comment]
I changed the title too.

**Comment by Ion-e** [comment]
Duplicate behaviour from https://github.com/nion-software/nion-internal/issues/109#issue-2357094971

**Comment by cmeyer** [comment]
Why was this closed as completed? It is still an open issue.

**Comment by Ion-e** [comment]
Issue partially fixed, however there seems to still be a corner case where this issue happens:

Screen 1 >start with swift maximised.
Drag Swift to screen 2 and drop at the top corner of the screen (This should move swift to screen 2 and maximise it in screen 2).
Minimise Swift.
Reopen Swift.
Swift will reopen in window 1.

**Comment by jamesrussell216** [comment]
@Brow71189 are you happy with closing this one in favour of us making a new, much smaller ticket for the corner case where this still doesn't work (which is hopefully much much less of a problem than this was!)?

**Comment by Brow71189** [comment]
If the initial bug is fixed, then yes, I'm fine with closing this.
Is there a commit associated with this fix? It would be good to link commits in comments that say "fixed" or "partially fixed" so that other people can follow more easily.

**Comment by jamesrussell216** [comment]
@Brow71189 this one I think ^^

**Comment by Brow71189** [comment]
Thanks @jamesrussell216. Also I'm fine with closing this since the minimize bug looks fixed.
