### ISSUE TITLE
Line plot log scale display breaks in some cases

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#944]
I haven't been able to figure out what exactly triggers this behavior, but below are some examples for how it looks. This is from a sequence of spectra, some work, and others don't:

Broken example:
![image](https://user-images.githubusercontent.com/16721195/227023640-b5dc00d6-6091-41f7-81f4-fa23020dc1f7.png)

Working example:
![image](https://user-images.githubusercontent.com/16721195/227024356-9094a6b0-8294-4034-96fa-ba6e1a0a6f1a.png)

Full sequence of spectra is in the zip file below. Set display to log style and scroll through the stack to see the problem.

[drive-download-20230322T193910Z-001.zip](https://github.com/nion-software/nionswift/files/11044330/drive-download-20230322T193910Z-001.zip)

**Comment by cmeyer** [comment]
I'll try to reproduce this. Generally, I have a vague feeling that this is a race condition between the display data calculation, which happens on a thread, and the calculation of the display limits for log scaling.

Also, I'll be working on this soon for the calibration-attached-to-the-display idea that I mentioned last week.
- #945

**Comment by cmeyer** [comment]
If this is a zero-log issue, see this article [Dealing with Zeros and Negative Values with a Log Scale](https://maxcandocia.com/article/2020/Aug/30/log-scale-zero-and-negative-values/).

**Comment by cmeyer** [comment]
See e95839c5602d009006ea88a648e5f78dc77c1ea4 for additional comments.
