### ISSUE TITLE
Activity panel can cause Swift to grow beyond the screen size

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#992]
The activity panel can grow to a substantial size if you add multiple computations attached to live data. If you have it open and Swift is not maximized on your screen, the window will be resized automatically when the activity panel grows. This can cause the window to grow beyond the screen bounds which is very confusing for users.
Maybe making the activity panel a scroll area widget could help with this. Of course you would have to scroll around to see all activities, but at least it would not make the main application grow.

**Comment by cmeyer** [comment]
See also:
- #930
